#pragma once

#include <emscripten/bind.h>
//#include <emscripten/val.h>

// EMSCRIPTEN_DECLARE_VAL_TYPE(Int8Array)
// EMSCRIPTEN_DECLARE_VAL_TYPE(Int16Array)
// EMSCRIPTEN_DECLARE_VAL_TYPE(Int32Array)
// EMSCRIPTEN_DECLARE_VAL_TYPE(Uint8Array)
// EMSCRIPTEN_DECLARE_VAL_TYPE(Uint16Array)
// EMSCRIPTEN_DECLARE_VAL_TYPE(Uint32Array)
// EMSCRIPTEN_DECLARE_VAL_TYPE(Float32Array)
// EMSCRIPTEN_DECLARE_VAL_TYPE(Float64Array)
// EMSCRIPTEN_DECLARE_VAL_TYPE(BigInt64Array)
// EMSCRIPTEN_DECLARE_VAL_TYPE(BigUint64Array)

